name: Build LOVE Package
description: Archives game folder into a .love file
inputs:
  output_folder:
    description: The folder in which the generated .love file will be placed
    required: true
  product_file:
    description: The basename of the file to be generated
    required: true
  product_name:
    description: The name of the game
    required: true
runs:
  using: composite
  steps:
    - name: Install tools
      uses: ./.github/actions/install-tools
    - name: Build LOVE package
      shell: bash
      run: |
        7z a -tzip -mx=6 -mpass=15 -mtc=off \
        "${{ inputs.output_folder }}/${{ inputs.product_file }}.love" \
        ./game/* -xr!.gitkeep
